## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Create compute instance and Exadata Cloud Service (Quarter Rack) database system in Oracle Cloud Infrastructure"
stackDescription: "This code will help you deploy a compute instance and Exadata Cloud Service (Quarter Rack) database system in Oracle Cloud"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: Required Configuration
  visible: true  
  variables:
  - db_admin_password
  - compartment_ocid

- title: Optional Configuration
  visible: true
  variables:  
  - ad_number
  - ad_name
  - instance_os
  - linux_os_version
  - instance_shape
  - db_system_shape
  - db_system_cpu_core_count
  - db_edition
  - db_name
  - db_version
  - db_home_display_name
  - db_disk_redundancy
  - db_system_display_name
  - db_cluster_name
  - hostname
  - host_user_name
  - n_character_set
  - character_set
  - db_workload
  - pdb_name
  - data_storage_size_in_gb
  - license_model
  - node_count
  - data_storage_percentage
  - db_auto_backup_enabled
  - db_auto_backup_window
  - db_recovery_window_in_days
  - release
    
variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources."

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  db_admin_password:
    type: password
    required: true
    title: "Database Admin password"
    description: "Type password for admin user in your DB System"
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  # Optional Configuration
  ad_number: 
    type: number
    required: false
    visible: false
  
  ad_name: 
    type: oci:identity:availabilitydomain:name
    required: false
    title: "Availability Domain"
    description: "Choose Availability Domain where you want to deploy your solution resources."
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_os: 
    type: enum
    required: false
    default: "Oracle Linux"
    title: "Operating system"
    description: "Choose Operating System for your compute instances."
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    default: "7.8"
    title: "Operating system version"
    description: "Choose Operating System version for your compute instances."
    enum:
      - "7.8"

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    default: "VM.Standard2.4"
    title: "Instance Shape"
    description: "Choose instance shape for your compute instances."
    dependsOn:
      compartmentId: ${compartment_ocid}

  db_system_shape:
    type: enum
    required: false
    default: "Exadata.Quarter2.92"
    title: "DB System Shape"
    description: "Choose the shape for your Exadata DBSystem."
    enum:
      - "Exadata.Quarter1.84"
      - "Exadata.Half1.168"
      - "Exadata.Full1.336"
      - "Exadata.Quarter2.92"
      - "Exadata.Half2.184"
      - "Exadata.Full2.368"
      - "Exadata.Quarter3.100"
      - "Exadata.Half3.200"
      - "Exadata.Full3.400"
  
  db_system_cpu_core_count:
    type: number
    required: false
    minimum: 4
    maximum: 400
    multipleOf: 1
    default: 4
    title: "DB System CPU core count"
    description: "Choose CPU core count for your Exadata DBSystem." 

  db_edition:
    type: enum
    required: false
    title: "DB Edition"
    default: "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
    description: "Choose DB Edition for your Exadata DBSystem." 
    enum:
      - "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"

  db_name:
    type: string
    required: false
    default: "aTFdb"
    title: "Database display name"
    description: "Type DB Name for your Exadata DBSystem." 

  db_version:
    type: enum
    required: false
    default: "12.2.0.1"
    description: "Choose DB version for your Exadata DBSystem." 
    enum:
      - "12.2.0.1"
      - "18c"
      - "19c"

  db_home_display_name:
    type: string
    required: false
    default: "MyTFDBHome"
    title: "Database home display name" 
    description: "Type database display for your Exadata DBSystem."  

  db_disk_redundancy:
    type: enum
    required: false
    default: "HIGH"
    title: "Database disk redundancy"
    description: "Choose database disk redundancy in your Exadata DBSystem."   
    enum:
      - "HIGH"
      - "NORMAL" 

  db_system_display_name:
    type: string
    required: false
    default: "MyTFDBSystem"
    title: "DB System display name"
    description: "Type display name for your Exadata DBSystem."  

  db_cluster_name:
    type: string
    required: false
    default: "TestCluster"
    title: "DB cluster name"
    description: "DB cluster name for your Exadata DBSystem."

  hostname:
    type: string
    required: false
    default: "myoracledb"
    title: "DB hostname" 
    description: "Type DB hostname in your Exadata DBSystem."  

  host_user_name:
    type: string
    required: false
    visible: false

  n_character_set:
    type: enum
    required: false
    default: "AL16UTF16"
    title: "Database NCharacter set"
    description: "Choose Database NCharacter set for your Exadata DBSystem." 
    enum:
      - "AL16UTF16"

  character_set:
    type: enum
    required: false
    default: "AL32UTF8"
    title: "Database Character set"
    description: "Choose Database Character set for your Exadata DBSystem." 
    enum:
      - "AL32UTF8"

  db_workload:
    type: enum
    required: false
    title: "Database workload"
    description: "Choose Database workload for your Exadata DBSystem." 
    enum:
      - "OLTP"

  pdb_name:
    type: string
    required: false
    title: "PDB name"
    description: "Choose PDB name for your Exadata DBSystem."

  data_storage_size_in_gb:
    type: number
    required: false
    default: 256
    minimum: 256
    maximum: 40960
    multipleOf: 256
    title: "Database storage size in GB"
    description: "Choose database storage size in GB for your Exadata DBSystem."

  license_model:
    type: enum
    required: false
    default: "LICENSE_INCLUDED"
    title: "Database license model"
    description: "Choose database license model for your Exadata DBSystem."
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  node_count:
    type: number
    required: false
    default: 1
    minimum: 1
    maximum: 4
    multipleOf: 1
    title: "Database node count"
    description: "Choose node numbers for your Exadata DBSystem."

  data_storage_percentage:
    type: enum
    required: false
    default: "40"
    title: "Database storage percentage"    
    description: "Choose database storage percentage for your Exadata DBSystem."
    enum: 
      - "40"
      - "80"

  db_auto_backup_enabled:
    type: boolean
    required: false
    default: true
    title: "Database Autobackup enabled"
    description: "Choose if database autobackup will be enabled for your Exadata DBSystem."

  db_auto_backup_window:
    type: enum
    required: false
    default: "SLOT_TWO"
    title: "Database Autobackup window"
    description: "Choose database autobackup window for your Exadata DBSystem." 
    enum:
      - "SLOT_TWO"    

  db_recovery_window_in_days:
    type: enum
    required: false
    default: "45"
    title: "Database Recovery window in days"
    description: "Choose database recovery window in days for your Exadata DBSystem." 
    enum:
      - "7"
      - "15"
      - "30"
      - "45"
      - "60"

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"

outputs:
  
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
